# CFLAGS và LDFLAGS
NVCC = nvcc
CFLAGS = -arch=sm_75
LDFLAGS = -lm -lcuda -lrt -L/usr/local/cuda/lib64 -lcudart

# Các rule để biên dịch
all: test train main

test: test.o
	$(NVCC) $(CFLAGS) -o test $(LDFLAGS) test.o src/network.o src/mnist.o src/layer/*.o src/loss/*.o src/optimizer/*.o src/layer/custom/*.o

test.o: test.cc
	$(NVCC) $(CFLAGS) --compile test.cc -I./

train: train.o 
	$(NVCC) $(CFLAGS) -o train $(LDFLAGS) train.o src/network.o src/mnist.o src/layer/*.o src/loss/*.o src/optimizer/*.o src/layer/custom/*.o

train.o: train.cc
	$(NVCC) $(CFLAGS) --compile train.cc -I./

main: main.o custom
	$(NVCC) $(CFLAGS) -o main $(LDFLAGS) main.o dnnNetwork.o src/network.o src/mnist.o src/layer/*.o src/loss/*.o src/optimizer/*.o

main.o: main.cc
	$(NVCC) $(CFLAGS) --compile main.cc -I./

custom: # Thực hiện các bước biên dịch cho các file custom
	# ... (Thêm các rule khác cần thiết cho việc biên dịch các file custom)

clean:
	rm -f test train main *.o src/*.o src/layer/*.o src/loss/*.o src/optimizer/*.o src/layer/custom/*.o

setup: network mnist layer loss optimizer

network:
	$(NVCC) $(CFLAGS) --compile src/network.cc -o src/network.o -I./

mnist:
	$(NVCC) $(CFLAGS) --compile src/mnist.cc -o src/mnist.o -I./

layer:
	nvcc -arch=sm_75 --compile src/layer/ave_pooling.cc -o src/layer/ave_pooling.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/conv.cc -o src/layer/conv.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/conv_gpu.cc -o src/layer/conv_gpu.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/fully_connected.cc -o src/layer/fully_connected.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/max_pooling.cc -o src/layer/max_pooling.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/relu.cc -o src/layer/relu.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/sigmoid.cc -o src/layer/sigmoid.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/layer/softmax.cc -o src/layer/softmax.o -I./ -L/usr/local/cuda/lib64 -lcudart


loss:
	nvcc -arch=sm_75 --compile src/loss/cross_entropy_loss.cc -o src/loss/cross_entropy_loss.o -I./ -L/usr/local/cuda/lib64 -lcudart
	nvcc -arch=sm_75 --compile src/loss/mse_loss.cc -o src/loss/mse_loss.o -I./ -L/usr/local/cuda/lib64 -lcudart

optimizer:
	# Biên dịch các file trong thư mục src/optimizer
