test.o: test.cc
	nvcc -arch=sm_75 --compile test.cc -I./ -L/usr/local/cuda/lib64 -lcudart

test: test.o
	nvcc -arch=sm_75 -o test -lm -lcuda -lrt test.o src/network.o src/mnist.o src/layer/*.o src/loss/*.o src/optimizer/*.o src/layer/custom/*.o -I./ -L/usr/local/cuda/lib64 -lcudart

test_model: test
	./test



train: demo.o 
	nvcc -arch=sm_75 -o demo -lm -lcuda -lrt demo.o src/network.o src/mnist.o src/layer/*.o src/loss/*.o src/optimizer/*.o src/layer/custom/*.o -I./ -L/usr/local/cuda/lib64 -lcudart

train.o: demo.cc
	nvcc -arch=sm_75 --compile demo.cc -I./ -L/usr/local/cuda/lib64 -lcudart

train_model: train
	./train